parameters:

services:
    imobile.website.admin.post:
        class: iMobile\Bundle\DataBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Posts, label: Posts }
        arguments: [null, iMobile\Bundle\DataBundle\Entity\Post, SonataAdminBundle:CRUD, @service_container]
