parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     istation
    database_user:     vihuvac
    database_password: dev

    mailer_transport:  smtp
    mailer_host:       smtp.gmail.com
    mailer_encryption: ssl
    mailer_port:       465
    mailer_user:       app.vihuvac@gmail.com
    mailer_password:   2dEFduXX

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    mongodb_server: mongodb://127.0.0.1:27017
    mongodb_database: istation 
